### ISSUE TITLE
can't import psio_test for python3 

### ISSUE THREAD

**Issue by criticanalytic** [syncope/psio_test#1]
>>> import psio_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/psio_test/psio_test/__init__.py", line 1, in <module>
    from psio_test import run
ImportError: cannot import name 'run'

Error occurs consistently for python 3.4, 3.5  -- something wrong in the import scheme?

**Comment by criticanalytic** [comment]
--> solution was a missing dot; the relative import is discouraged/wrong
rather: state the current directory as active by explicitly putting a dot in front the module name
